version: "3.9"
    
services:
  graphite:
    # query test metric raw data
    # http://localhost:8080/render?format=json&target=randomWalk(%22machines.test1%22)
    image: graphiteapp/graphite-statsd:latest
    restart: always
    ports:
      - "8080:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress

  grafana:
    # default dashboard
    # http://localhost:3000/d/21aYM4xnz/new-dashboard?orgId=1
    # test embed
    # http://localhost:3000/d-solo/21aYM4xnz/machine-dashboard?orgId=1&from=now-1h&to=now&panelId=5&refresh=5s&kiosk&var-machine_name=machine_2
    depends_on:
      - graphite
    image: grafana/grafana-oss@sha256:cf81d2c753c8d14cf0324d881e49f42d400347d256e473856e1bda02eb520a99
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - ./dashboards:/dashboards
      - ./config/grafana.ini:/etc/grafana/grafana.ini
    environment:
        GF_INSTALL_PLUGINS: "natel-discrete-panel"

  nginx:
    # request the index page via
    # http://localhost:3080

    # sample video
    # rtmp://localhost:1935/vod/file_example_MP4_480_1_5MG.mp4
    # rtmp://localhost:1935/vod/mp4:file_example_MP4_480_1_5MG.mp4

    # nginx grafana proxy
    # http://localhost:3080/graphs/d/21aYM4xnz/new-dashboard?orgId=1
    # http://localhost:3080/graphs/d-solo/21aYM4xnz/machine-dashboard?orgId=1&from=now-1h&to=now&panelId=5&refresh=5s&kiosk&var-machine_name=machine_2
    
    # nginx dashboard proxy
    # http://localhost:3080/dashboard/machine?machine_name=01&machine_serial=APA-AU-1231-34-X

    image: tiangolo/nginx-rtmp
    restart: always
    ports:
      - "3080:80"
      - "1935:1935"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html
